In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as pl
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
trd=pd.read_csv('loan_train.csv')
tsd=pd.read_csv('loan_test.csv')

In [16]:
trd.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [84]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
trd['Loan_Status']=label_encoder.fit_transform(trd['Loan_Status'])
trd['Education']=label_encoder.fit_transform(trd['Education'])
trd['Property_Area']=label_encoder.fit_transform(trd['Property_Area'])
trd['Gender']=label_encoder.fit_transform(trd['Gender'])
trd['Property_Area']=label_encoder.fit_transform(trd['SE'])

In [41]:
trd.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [91]:
trd['Gender'].replace('NaN',1,inplace=True)
trd['Married'].replace('No',0,inplace=True)

In [92]:
trd.head(24)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1,1.0,0,0,No,5849,0.0,146.412162,360.0,1.000000,2,1
1,LP001003,1,1.0,1,0,No,4583,1508.0,128.000000,360.0,1.000000,0,0
2,LP001005,1,1.0,0,0,Yes,3000,0.0,66.000000,360.0,1.000000,2,1
3,LP001006,1,1.0,0,1,No,2583,2358.0,120.000000,360.0,1.000000,2,1
4,LP001008,1,1.0,0,0,No,6000,0.0,141.000000,360.0,1.000000,2,1
5,LP001011,1,1.0,2,0,Yes,5417,4196.0,267.000000,360.0,1.000000,2,1
6,LP001013,1,1.0,0,1,No,2333,1516.0,95.000000,360.0,1.000000,2,1
7,LP001014,1,1.0,3+,0,No,3036,2504.0,158.000000,360.0,0.000000,1,0
8,LP001018,1,1.0,2,0,No,4006,1526.0,168.000000,360.0,1.000000,2,1
9,LP001020,1,1.0,1,0,No,12841,10968.0,349.000000,360.0,1.000000,1,0
10,LP001024,1,1.0,2,0,No,3200,700.0,70.000000,360.0,1.000000,2,1
11,LP001027,1,1.0,2,0,NaN,2500,1840.0,109.000000,360.0,1.000000,2,1
12,LP001028,1,1.0,2,0,No,3073,8106.0,200.000000,360.0,1.000000,2,1
13,LP001029,1,1.0,0,0,No,1853,2840.0,114.000000,360.0,1.000000,0,0
14,LP001030,1,1.0,2,0,No,1299,1086.0,17.000000,120.0,1.000000,2,1
15,LP001032,1,1.0,0,0,No,4950,0.0,125.000000,360.0,1.000000,2,1
16,LP001034,1,1.0,1,1,No,3596,0.0,100.000000,240.0,0.842199,2,1
17,LP001036,0,1.0,0,0,No,3510,0.0,76.000000,360.0,0.000000,2,0
18,LP001038,1,1.0,0,1,No,4887,0.0,133.000000,360.0,1.000000,0,0
19,LP001041,1,1.0,0,0,NaN,2600,3500.0,115.000000,342.0,1.000000,2,1
20,LP001043,1,1.0,0,1,No,7660,0.0,104.000000,360.0,0.000000,2,0
21,LP001046,1,1.0,1,0,No,5955,5625.0,315.000000,360.0,1.000000,2,1
22,LP001047,1,1.0,0,1,No,2600,1911.0,116.000000,360.0,0.000000,1,0
23,LP001050,14,1.0,2,1,No,3365,1917.0,112.000000,360.0,0.000000,0,0